config/routes.rb
Rails.application.routes.draw do

  root to: "cocktails#index"

  resources :cocktails, only: [ :new, :create, :show ] do
    resources :doses, only: [:new, :create]
  end
    delete "/doses/:id", to: "doses#destroy", as: "dose"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PothoscocktailsUploader

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true

  validates :cocktail, uniqueness: {scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def new
   @cocktail = Cocktail.new
  end

  def create
   @cocktail = Cocktail.new(cocktail_params)
   if @cocktail.save
     redirect_to cocktail_path(@cocktail)
   else
     render :new
   end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def index
    @cocktails = Cocktail.all
  end

 private

 def set_cocktail
   @cocktail = Cocktail.find(params[:id])
 end

 def cocktail_params
   params.require(:cocktail).permit(:name, :photo)
 end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail_id = @cocktail.id
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail_id)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
end


  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1509807995916-c332365e2d9e?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=4c8d364e633e2015fbac047f327ce098&auto=format&fit=crop&w=1271&q=80');">
  <div class="banner-content">
    <h1>Fancy Cocktails</h1>
    <p>Have some drinks with us!</p>
  </div>
</div>


<div class="container">
  <div class="row">

    <% @cocktails.each do |c| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card">
      <div class="cardphoto" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path c.photo, height: 300, width: 400, crop: :fill %>');">
      </div>
        <div class="card-description">
          <%= link_to c.name, cocktail_path(c)%>
        </div>

      </div>
    </div>
    <% end %>

  </div>
</div>

<div class="new_cocktail_button">
<button type="button" class="btn btn-info " >
<%= link_to "New Cocktail", new_cocktail_path %>
</button>
</div>

app/views/cocktails/new.html.erb
<h1> Please type the new cocktail here </h1>
<p><%= render "shared/form" %></p>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <h1><%= @cocktail.name %></h1>
    <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

    <h2>Add the combination</h2>
    <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient, include_hidden: false %>
    <%= f.button :submit %>
    <% end %>


    <h3>Ingredients</h3>
    <% @cocktail.doses.each do |dose|  %>
    <div class="ingredient flex-container">
    <p class="dose">
      <%= dose.description %> <%= dose.ingredient.name%>
    </p>
    <%= link_to "Delete", dose_path(dose.id),
    method: :delete,
    data: { confirm: "Are you sure?" } %>
    </div>
    <% end %>
<br>
    <%= link_to "Go back to menu", root_path%>
  </div>
</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit %>
<% end %>